### ISSUE TITLE
Proposal: add _flush to Writable streams 

### ISSUE THREAD

**Issue by markstos** [nodejs/readable-stream#112]
@TomFrost made a good case for this pre-fork:

https://github.com/joyent/node/issues/7631

There was also significant discussion previously in this issue:
https://github.com/joyent/node/issues/7348

 @TomFrost also implemented a workaround that is published on npmjs.org:

https://www.npmjs.com/package/flushwritable

Perhaps it will be helpful in considering the issue.

I'm one of the other developers from the previous thread that would also find it to be useful.

**Comment by calvinmetcalf** [comment]
This is something I've needed and had to implement my own half baked
implementation.   I'd be happy to champion this (do we do that?)

**Comment by domenic** [comment]
+1, got one of these in WHATWG streams already (under the name "close", although now I am contemplating whether flush is nicer).

**Comment by calvinmetcalf** [comment]
The tricky thing is that transform flush is after writable half has
finished but before the readable one is finished. For writable ones we'd
need it to be earlier so either a breaking change or a different name like
close.

**Comment by chrisdickinson** [comment]
@calvinmetcalf I'm a little confused by:

> The tricky thing is that transform flush is after writable half has finished but before the readable one is finished.

My impression is that we would preserve this behavior, and extend [this behavior](https://github.com/iojs/io.js/blob/v1.x/lib/_stream_transform.js#L116-L123) to Writables as well. Am I misunderstanding?

I am also curious: what is the order of events?

1. emit prefinish
2. _flush
3. emit finish

OR:

1. emit _flush
2. prefinish
3. emit finish

**Comment by vkurchatkin** [comment]
> My impression is that we would preserve and extend this behavior to Writables as well. Am I misunderstanding?

there is no point in flushing writable after finish. the whole idea is to defer finish

**Comment by calvinmetcalf** [comment]
@chrisdickinson like @vkurchatkin said we want to defer finish, adding in new function (like calling it close) that fires earlier would likely be the only backwards compatible way to do it, we could leave _flush in but depreciate it.

**Comment by vkurchatkin** [comment]
@calvinmetcalf I was thinking about `_finish`. I want `_close` to be used to close underlying resource after finish.

**Comment by sonewman** [comment]
I am not that opinionated about this. Is there any reason why we couldn't move it from `transform`?

**Comment by calvinmetcalf** [comment]
@vkurchatkin I  was assuming closing resources would be a use case for this

@sonewman because the transform one happens after finish is emitted  and we'd want it to delay finish being emitted.

**Comment by mafintosh** [comment]
Why not call it `._end`?
Similar to how `.write` calls `._write` internally `.end` would call `._end` before emitting `finish`

**Comment by calvinmetcalf** [comment]
@mafintosh and then simply end when passing it to the simplified constructor

**Comment by mafintosh** [comment]
@calvinmetcalf yea! and transforms would support both flush and end (different use cases). i know this would simplify a lot of my code.

**Comment by sonewman** [comment]
@calvinmetcalf `prefinish` is emitted before `finish`
```javascript
function prefinish(stream, state) {
  if (!state.prefinished) {
    state.prefinished = true;
    stream.emit('prefinish');
  }
}

function finishMaybe(stream, state) {
  var need = needFinish(stream, state);
  if (need) {
    if (state.pendingcb === 0) {
      prefinish(stream, state);
      state.finished = true;
      stream.emit('finish');
    } else
      prefinish(stream, state);
  }
  return need;
}
```
[lib/_stream_writable.js#L464-L482](https://github.com/iojs/io.js/blob/v1.x/lib/_stream_writable.js#L464-L482)

**Comment by sonewman** [comment]
Also i don't think it would be right for `_flush` to be called after `finish` since it is usually where you would push some last bit of protocol data...

**Comment by sonewman** [comment]
The thing is, there is always going to be more, and more(,...and more,...) new things people are going to want, to instrument their stream in some specific way. Open up a model for the underlying sources and those things are easy for anyone to instrument to any requirement.

To be clear, I am **not** saying any of these ideas are bad, as they are generic and useful.

But IMO going forward we need to open up this cycle/internals for people to customise at their will, meaning the base of streams can be simple and avoid continuous scope creep.

*@sonewman - gets off soap box*

**Comment by calvinmetcalf** [comment]
sorry it's that finish can be called before _flush is **done** if it's async. I seem to remember testing what would happen if you did delay it and it causing quite a few node transform streams to break.

**Comment by sonewman** [comment]
@calvinmetcalf hmmm, interesting. I can see how that would be true, since `_flush` is called as of an event, then `finish` is triggered synchronously afterwards. If we moved `_flush` to the `writable` stream, we could remove the internal dependency on that event completely (although we would not be able to remove it, since it is used by `http`)

**Comment by mafintosh** [comment]
the `prefinish` event isn't super useful since you can't do anything async before `finish` happens

**Comment by mafintosh** [comment]
@sonewman @calvinmetcalf moving the flush function to writable streams is a major change since the flush function currently is called before the *readable* part of the stream ends (not the writable).

**Comment by calvinmetcalf** [comment]
so _flush is part of the public api and when it is called [is documented](https://iojs.org/api/stream.html#stream_events_finish_and_end). This was why I was suggesting a new function name.

**Comment by sonewman** [comment]
I think I am +1 on doing this, it seems like that would actually be useful.

@mafintosh `prefinish` is emitted in [lib/_stream_writable.js#L467](https://github.com/iojs/io.js/blob/v1.x/lib/_stream_writable.js#L467), forgive me if I am wrong, but I don't see why it would have any affect on the readable side of a transform stream.

**Comment by mafintosh** [comment]
@sonewman my point is that the `._flush` function used in transform streams is used to do stuff before the readable part of a stream ends - not the writable.

``` js
var transform = stream.Transform({
  transform: function (data, enc, cb) {
    cb(null, data)
  },
  flush: function(cb) {
    setTimeout(function () {
      transform.push('world')
      cb()
    }, 1000)
  }
})

transform.on('data', function (data) {
  console.log(data.toString())
})
transform.on('finish', function() {
  console.log('(finish)')
})
transform.on('end', function() {
  console.log('(end)')
})
transform.write('hello')
transform.end()
```

running the above will result in

```
hello
(finish)
world
(end)
```

**Comment by mafintosh** [comment]
which is why i think having it being called something like `end` would be useful. this would allow you to async stuff before `finish` is emitted.

``` js
var stream = require('stream')

var transform = stream.Transform({
  transform: function (data, enc, cb) {
    cb(null, data)
  },
  end: function (cb) {
    setTimeout(function() {
      transform.push('before finish')
      cb()
    }, 1000)
  },
  flush: function (cb) {
    setTimeout(function () {
      transform.push('world')
      cb()
    }, 1000)
  }
})

transform.on('data', function (data) {
  console.log(data.toString())
})
transform.on('finish', function() {
  console.log('(finish)')
})
transform.on('end', function() {
  console.log('(end)')
})
transform.write('hello')
transform.end()
```

-->

```
hello
before finish
(finish)
world
(end)
```

**Comment by sonewman** [comment]
@mafintosh whether something comes after `_flush` is probably a separate discussion.

But the point I am trying to make is that `_flush` when called should allow for asynchronicity like this:
```javascript
function finishWritable(stream, state) {
  if (state.pendingcb === 0) {
    state.finished = true;
    stream.emit('finish');
  }
}

function prefinish(stream, state) {
  if (!state.prefinished) {
    state.prefinished = true;
    stream.emit('prefinish');
    
    if ('function' === typeof stream._flush)
      stream._flush(() => finishWritable(stream, state));
    else
      finishWritable(stream, state);
  }
}

function finishMaybe(stream, state) {
  var need = needFinish(stream, state);
  if (need)
      prefinish(stream, state);

  return need;
}
```

**Comment by chrisdickinson** [comment]
@vkurchatkin Ah, I see. Transform currently hooks onto `prefinish`, but `flush` does not block `finish`.

@mafintosh I'm -1 on calling it "end". Between "end" events, "end" methods, and the "finish" events, the term is a bit overloaded as it stands.

@sonewman I agree that the proposed `flush` should be able to "block" writables from emitting finish. This is *currently* incompatible with `Transform#_flush`, but what if we took advantage of the simplified stream constructor interface to give the old-style `TransformSubclass.prototype._flush = <fn>` different semantics from new-style `Tranfrom({flush: (cb) => {}})` creation?

**Comment by chrisdickinson** [comment]
Arg, yes, `flush` as a shorthand option has already been released. Changing that behavior *would* be breaking, though probably only minimally so due to how recently introduced it was.

Alternatively, `Transform` can have an "oddball" flush that *cannot* block "finish", while all other writable finish functions would be able to.

**Comment by mafintosh** [comment]
@chrisdickinson having simple constructor `flush` and `.prototype._flush` do different things seems weird though. couldn't `flush` on Transforms just block *both* `finish` and `end`?

is there a use case for adding `._flush` on Readable streams as well?

**Comment by chrisdickinson** [comment]
@mafintosh Re: delaying `finish` until `flush` completes, quoting @calvinmetcalf:

> sorry it's that finish can be called before _flush is done if it's async. I seem to remember testing what would happen if you did delay it and it causing quite a few node transform streams to break.

If we use the simplified constructor API to introduce this behavior, we can sidestep that breakage, but still introduce the functionality for all Writables (duplexes and transforms included) It is a little weird that `new Transform({flush: (cb) => {}})` will be different than `t = new Transform; t._flush = () => {}`, but we should strongly discourage use of the latter usage pattern for all streams going forward.

--------

I just noticed this when rereading the thread, but one of the [originally linked issues](https://github.com/joyent/node/issues/7631) suggested this feature for the purposes of batch writes – specifically, so that a batching writer can be made aware of the end of the stream and output the rest of its data before close. However, we *already have* a mechanism for batching writes – `writev`, `cork`, and `uncork` – which *should* make a userland batching writestream superfluous.

Are there other valid uses for this feature outside of batch writes?

**Comment by mafintosh** [comment]
I have a couple of use cases myself:

In [pumpify](https://github.com/mafintosh/pumpify) (turns multiple writable/readable streams into a single one) I don't want to emit `finish` until the *last* stream in the pipeline has emitted finish after all writes are done. Since we don't have a `flush` function on writable streams I do a bunch of hacks to do this.

In [content-addressable-blob-store](https://github.com/mafintosh/content-addressable-blob-store) we write to a tmp file that we wan't to move somewhere before emitting `finish` after all writes are done.

**Comment by mafintosh** [comment]
@chrisdickinson @calvinmetcalf we could just break `prototype._flush` and bump the major version \o/

**Comment by calvinmetcalf** [comment]
@chrisdickinson writev, cork, and uncork don't actually do the trick because they must be explicitly called by the caller so don't work cases like when the stream is being piped too. 

Besides batch writes there is also closing underlying resources hence why the name _close came up. While _end is a bit confusing due to the event it d ones fit with the pattern of write,  writev,   and read. 

@mafintosh I totally don't think it's worth a major version bump, I'd call it __flush before bumping the major.

**Comment by sonewman** [comment]
Hmm, i don't know. I can't see how `finish` would be emitted asynchronous in a transform stream, but perhaps I am missing something. I guess it could break any modules, which were rely on a transform to emit that it is finished before it flushes...

**Comment by chrisdickinson** [comment]
Noting this here: it seems like there's interest in `flush` for the purposes of `net.Socket` cleanup in core (per @indutny in the io.js IRC channel.)

**Comment by indutny** [comment]
I will expand my thoughts:

We have a problem with TLS streams in core at the moment. Current implementation calls `socket.shutdown()` on `finish` event, and in many cases does not wait for the completion before destroying the socket. This thing is totally fine, unless you are doing TLS, because TLS sends additional packet on `shutdown()` and prematurely closing the socket will lead to errors, or non-graceful destruction of connection.

`_flush` would help there a lot.

**Comment by indutny** [comment]
Yeah, and my use case needs callback.

**Comment by chrisdickinson** [comment]
@indutny Curious: if there's a write going out during `flush`, would you expect `flush` to be called again once that write has completed?

**Comment by indutny** [comment]
@chrisdickinson nope. In case of TLS, this write is happening internally in C++.

**Comment by indutny** [comment]
Just in case, I'm going to stub out some implementation and share it with you guys.

**Comment by indutny** [comment]
See https://github.com/iojs/io.js/pull/1164

**Comment by indutny** [comment]
So far I haven't reunified it with transform, so it is called `__flush` as suggested here.

**Comment by indutny** [comment]
Finished the PR there, PTAL.

**Comment by mcollina** [comment]
This is currently being proposed in https://github.com/nodejs/node/pull/12828.

**Comment by calvinmetcalf** [comment]
merged into node as `final`
