### ISSUE TITLE
Working Group governance model & charter

### ISSUE THREAD

**Issue by mcollina** [nodejs/readable-stream#248]
From the Collaborator Summit in Austin, TX, it emerged the fact that the Streams WG does not have a proper charter, even if it has been chartered when the Foundation has been created. I think we should fill this in, and officialise ourselves. The alternative is to move to a less formal group, a "team".

As I understood, a chartered wg has a a delegation from tsc/ctc.

@williamkapke can probably clarify some of this, and help us with the proper paperwork.

As an example, see https://github.com/nodejs/security-wg/pull/9.

**Comment by calvinmetcalf** [comment]
Ok so it's mainly a paperwork thing?

**Comment by mcollina** [comment]
I think so, yes. We might need a formal vote or something like that.
I think we all are extremely bad at this, so I hope if @williamkapke could help us.

**Comment by williamkapke** [comment]
Hey @mcollina! Thanks for following up on this.

Here's the deal. Ya'll have an official Charter listed in [WORKING_GROUPS.md](https://github.com/nodejs/node/blob/master/WORKING_GROUPS.md#streams)
... but your repo doesn't have the docs that are _preferred_. I need to say it that way because Working Groups are autonomous... meaning you don't NEED to do anything. But, for the community's sake- it's nice to be uniform.

The templates for the docs are here:
https://github.com/nodejs/TSC/blob/master/WORKING_GROUPS.md#bootstrap-governance

Also- WG are supposed to have their chartered revoked when their work is complete. Maybe the Streams work will NEVER be complete? Some WGs are like that.

**- OR -**
The working group could choose to be a team instead- which is less formal. There really isn't much of a difference between them. Working Groups are given autonomy and delegated full control over the things listed in their charter and teams are not. But in practice, that doesn't really mean much because the CTC/TSC would MUCH rather delegate work out to people specialized/focused on being awesome at it... so the control is given anyhow. Look at LTS, Security, or Version Management for examples.

So, being the "Streams Team" would operate the same as it does now- but the boilerplate docs wouldn't be expected.

**Comment by mcollina** [comment]
I think being a WG makes more sense because `readable-stream` is somewhat autonomous, given than we support _all_ the versions of Node and the browsers (see https://github.com/nodejs/readable-stream/blob/master/.travis.yml). It _might_ qualify as a standalone project if/when the dependency between this and core is reversed.

> Also- WG are supposed to have their chartered revoked when their work is complete. Maybe the Streams work will NEVER be complete? Some WGs are like that.

The goal here is maintenance and fostering the community around streams. During 2016, we helped both gulp and node-serialport. As far as this, the streams work will _never_ be completed.

**Comment by mcollina** [comment]
@nodejs/streams what do you think? WG or team?

**Comment by calvinmetcalf** [comment]
wg makes sense

**Comment by mcollina** [comment]
@mafintosh @yoshuawuyts @chrisdickinson @nodejs/streams what do you think?

**Comment by mafintosh** [comment]
Sure, wg

**Comment by yoshuawuyts** [comment]
Wg sounds good (:
