### ISSUE TITLE
Browser block usage breaks instanceof(Stream)

### ISSUE THREAD

**Issue by tardoin** [nodejs/readable-stream#449]
This is my first issue and it's a bit of a complicated one with several pieces, so bear with me.

We recently updated webpack to a change where it treats the target electron-renderer as using the browser{} blocks in package.json. This package has such a block.
The problem is that if I create a new readableStream.Readable(), this does:

var Stream = require('./internal/streams/stream');

The "browser" version of this maps to lib\internal\streams\stream-browser.js.
This simply exports EventEmitter.

This then breaks anything doing instanceof(Stream) since Stream is no longer in the chain. Our particular example was Archiver uses lazystream which uses readable-stream.

I'm not really sure if this is totally your problem (I've read instanceof is not reliable, although it seems to be used a lot in various places all over) but thought I'd report it anyway. Maybe a better stream-browser.js or a way to tell it to go ahead and use the real stream could be given.

**Comment by mcollina** [comment]
Would you like to send a PR?

**Comment by benjamingr** [comment]
Making `instanceof` pass (with Symbol.hasInstance) is easy - but I don't think it would actually fix anything since like you noticed - `Stream` is just an `EventEmitter` and not a [`Stream`](https://github.com/nodejs/node/blob/master/lib/internal/streams/legacy.js#L10).

Probably possible to copy that file along _and_ override `Symbol.hasInstance`.
