### ISSUE TITLE
Better Typescript support

### ISSUE THREAD

**Issue by james-pre** [nodejs/readable-stream#546]
At the moment, types are maintained separately from `readable-stream` in `@types/readable-stream`. If `readable-stream` included types, they could be updated along with implementation changes, and users would only need to install one package.

I think that a potential rewrite in Typescript is feasible, and would be willing to work on it if the maintainer(s) are open to it. If a TS rewrite is too much, even including a declaration would be helpful. We can also use `@types/readable-stream` as a starting place.

Please let me know what you think.

**Comment by MattiasBuelens** [comment]
As it currently stands, `@types/readable-stream` is being maintained together with `@types/node`, which both live in the [DefinitelyTyped monorepo](https://github.com/DefinitelyTyped/DefinitelyTyped). Moving the type definitions from DefinitelyTyped to this repository would make it difficult to keep this project's typings in sync with Node.js typings, since they'd be split across two repositories.

Rewriting this project to TypeScript would actually make it *more difficult* to maintain. [As explained in the README](https://github.com/nodejs/readable-stream/blob/v4.6.0/README.md), this project is a mirror of [the streams implementation that ships with Node](https://github.com/nodejs/node/tree/v18.16.0/lib), which is written in JavaScript. The mirroring process is fully automated: [`npm run build`](https://github.com/nodejs/readable-stream/blob/v4.6.0/build/build.mjs) downloads an official Node.js release, pulls out the `stream` files, applies a few patches to make it run outside of Node, and that's basically it. Rewriting to TypeScript would break this process, requiring all future updates to be *manually* ported from the original JavaScript implementation to this separate TypeScript implementation. We simply don't have the resources to do that.

I think the status quo is the best we can do for now. Maybe someday Node.js itself could be rewritten in TypeScript and we wouldn't need either `@types/node` or `@types/readable-stream`, but I don't think that's going to happen. 😅
